baseURL = "https://example.com"
languageCode = "en-us"
title = "妖精円卓領域 アヴァロン･ル･フェ"
theme = "kagome"
paginate = 7
copyright = "© 2023 <a href=\"https://github.com/AvalonLeFae\">AvalonLeFae</a>."
hasCJKLanguage = true
#defaultContentLanguage="zh-cn"
disqusShortname = 'example-com'

# 作者信息
[author]
name = "Mélusine"
email = "xx@xx.com"
description = "Hollow Heart Albion"
avatar = "https://fgo.wiki/images/0/0b/%E3%83%A1%E3%83%AA%E3%83%A5%E3%82%B8%E3%83%BC%E3%83%8C%E6%BB%A1%E7%A0%B4.png"
# 菜单/导航栏
[menu]
# 顶部导航栏
[[menu.main]]
identifier = "/HOME"
name = "HOME"
url = "/"
weight = 1
[[menu.main]]
identifier = "/CATEGORIES"
name = "CATEGORIES"
url = "/CATEGORIES"
weight = 2
[[menu.main]]
identifier = "/TAGS"
name = "TAGS"
url = "/TAGS"
weight = 3


# 底部社交图标
[[menu.social]]
identifier = "github"
name = "github"
url = "https://github.com/AvalonLeFae"
weight = 1
[[menu.social]]
identifier = "zhihu"
name = "zhihu"
url = ""
weight = 2
[[menu.social]]
identifier = "weibo"
name = "weibo"
url = ""
weight = 3
# URL格式
[permalinks]
posts = "/:section/:year:month:day:15:04/"
files = "/:section/:year:month:day:15:04/"
docs = "/:section/:year:month:day:15:04/"

# 主题相关配置项
[params]
keywords = ['theme', 'kagome']
description = ""
mainSections = ["golang","extra","home","hugo","git"]
# 国内备案号
beian = ""
# TOC目录出现字符长度限制
toc_show_len = 300

[params.analytics]
baidu = ""

[params.widget]
# 相关文章推荐数量
articles_count = 6
# 分类相关显示数量
categories_count = 6
# 标签相关显示数量
tags_count = 12

[params.aplayer]
theme = "#b7daff"
autoplay = false
loop = "none"
mutex = true

[params.dplayer]
theme = "#b7daff"
autoplay = false
loop = false
mutex = true

[privacy]
[privacy.disqus]
#关闭评论页面
disable = true